Repository neurobagel/recipes, pull requests merged in 2024-08, with the labels that each got.

#73 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/pull_request_template.md
  .github/workflows/release.yaml
Labels: _bot

#72 [ENH] Removed `local_node_query` profile
  README.md
  docker-compose.yml
  docs/neurobagel_environment_variables.tsv
  template.env
Labels: pr-minor-breaking

#77 [MNT] Renamed `NB_QUERY_URL_PATH` env var to `NB_QUERY_APP_BASE_PATH`
  CHANGELOG.md
  docker-compose.yml
  docs/neurobagel_environment_variables.tsv
  template.env
Labels: pr-internal

#78 [MNT] Updated `compatibility.yaml` file and e2e tests
  .github/workflows/compatibility.yaml
  README.md
  cypress/e2e/simple-test.cy.js
  docker-compose.yml
Labels: pr-internal

#80 [REF] Remove container-internal ports and unneeded graph config vars
  docker-compose.yml
  docs/neurobagel_environment_variables.tsv
  template.env
Labels: pr-minor
