Repository neurobagel/recipes, pull requests merged in 2024-10, with the labels that each got.

#89 [FIX] Update `nb_vocab.ttl` with imaging/phenotypic sessions and pipeline classes
  vocab/nb_vocab.ttl
Labels: pr-bug-fix

#90 [MNT] Removed `.env` volume from `graph` service
  docker-compose.yml
  scripts/graphdb_setup.sh
  scripts/setup.sh
Labels: pr-internal

#92 [ENH] Update reference example JSONLD with derivatives metadata
  data/example_synthetic_pheno-bids-derivatives.jsonld
Labels: release, pr-minor
