Repository neurobagel/recipes, pull requests merged in 2025-03, with the labels that each got.

#114 [TST] Add smoke test of `full_stack` deployment steps
  .github/workflows/test.yml
Labels: skip-release

#116 [FIX] Fix typo and rename test.yml to test_setup.yml
  .github/workflows/test_setup.yml
Labels: skip-release

#118 [TST] Set up e2e compatibility test
  .github/actions/test-setup/action.yml
  .github/workflows/test_fullstack_e2e.yml
  .github/workflows/test_setup.yml
  cypress/e2e/fullstack-test.cy.js
  package-lock.json
  package.json
Labels: skip-release, flag:check

#121 [TST] Add a second open node to the deployment e2e tests
  .github/actions/test-setup/action.yml
  cypress/e2e/fullstack-test.cy.js
Labels: pr-tests
