Repository neurobagel/recipes, pull requests merged in 2025-04, with the labels that each got.

#126 [FIX] Fix issues with e2e test
  .github/actions/test-setup/action.yml
  cypress/e2e/fullstack-test.cy.js
Labels: pr-tests

#125 [ENH] Introduce new NB_GRAPH_MEMORY variable
  docker-compose.yml
  scripts/setup.sh
  template.env
Labels: pr-patch

#127 [DOC] new Graph memory ENV variable
  docs/neurobagel_environment_variables.tsv
Labels: release, pr-documentation

#132 [FIX] Fix syntax error in setup.sh with setting the GraphDB memory limit (`NB_GRAPH_MEMORY`)
  scripts/setup.sh
Labels: release, pr-bug-fix
